# 


development:
  clients:
    default:
      database: nw-db-iot
      hosts:
        - 103.59.95.173:27017
      options:
        # The name of the user for authentication.
        user: 'iot'
        # The password of the user for authentication.
        password: "password"
        # The user's database roles.
        roles:
           - 'dbOwner'
        auth_mech: :scram
        auth_source: admin
  options:
  raise_not_found_error: false
test:
  clients:
    default:
      database: nw-db-iot
      hosts:
        - 103.59.95.173:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  options:
  raise_not_found_error: false